version: "3"

services:
  php:
    container_name: myWork-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ../app:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: myWork-nginx
    ports:
      - 8090:80
    volumes:
      - ../app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:5.7
    container_name: myWork-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wk
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3316:3306

